vqgan_ckpt: null 
vae_ckpt: null
# vae_ckpt: 'stabilityai/sd-vae-ft-mse-original'

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: 32
diffusion_depth_size: 128
diffusion_num_channels: 4
dim_mults: [1,2,4,8]
results_folder: "./checkpoints/ddpm/"
results_folder_postfix: ''
load_milestone: False
cond_dim: 512 

batch_size: 2
num_workers: 2
logger: wandb
objective: pred_x0
save_and_sample_every: 5000
denoising_fn: Unet3D

train_lr: 1e-4
# train_lr: 2e-7

timesteps: 1000 # number of steps
sampling_timesteps: 500 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])

# loss_type: l1_lpips
loss_type: l1_lpips

train_num_steps: 60000000 # total training steps

gradient_accumulate_every: 2 # gradient accumulation steps
# gradient_accumulate_every: 16 # gradient accumulation steps

ema_decay: 0.995 # exponential moving average decay
# ema_decay: 0.999 # exponential moving average decay


# amp: True # turn on mixed precision
amp: False # turn on mixed precision

num_sample_rows: 1

max_grad_norm: 1.0
# max_grad_norm: 0.1

gpus: 0
l1_weight : 1.0

perceptual_weight : 0.01
# perceptual_weight : 0.0


discriminator_weight : 0.0 
classification_weight: 0.0
classifier_free_guidance: False
lora: True
lora_first: False
medclip: True

# name_dataset: LIDC # The dataset name for normalization: options are RSPECT, LIDC, CTPA
# dataset_min_value: -1024 # min value of the dataset for normalization
# dataset_max_value: 3071  # max value of the dataset for normalization

name_dataset: LIDC # The dataset name for normalization: options are RSPECT, LIDC, CTPA
dataset_min_value: -12.911299 # min value of the dataset for normalization
dataset_max_value: 9.596558  # max value of the dataset for normalization

#name_dataset: RSPECT
#dataset_min_value: -8.749182 # min value of the dataset for normalization
#dataset_max_value: 8.710065  # max value of the dataset for normalization
